import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(scriptDir, '..');
const packageJsonPath = resolve(rootDir, 'package.json');
const versionFilePath = resolve(rootDir, 'src/version.ts');

const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

if (typeof version !== 'string' || version.length === 0) {
  throw new Error(`Expected package.json version to be a non-empty string, got ${String(version)}`);
}

const nextContent = `// Auto-generated by scripts/sync-version.mjs. Do not edit manually.
export const VERSION: string = ${JSON.stringify(version)};
`;

const prevContent = existsSync(versionFilePath) ? readFileSync(versionFilePath, 'utf8') : null;

if (prevContent !== nextContent) {
  writeFileSync(versionFilePath, nextContent);
}
